language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

script:
  - unset CI 
  - npm run build

deploy:
  provider: heroku
  api_key: c5359a19-f5ea-4a4b-938b-283501d8bd8b
  app: parking-system-mobile

on:
  branch: master